name: bidalle
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.0
  - pytorch=1.7.1
  - torchvision=0.8.2
  - pip:
    - wandb
    - albumentations
    - einops
    - tqdm
    - omegaconf
    - transformers
    - pytorch-lightning==1.0.8